version: '3.7'

services:
    app:
        build:
            args:
                user: toner
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: toner
        container_name: toner-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - toner

    mysql:
        image: mysql:5.7
        container_name: toner-db
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: controle-toner
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - toner

    nginx:
        image: nginx:1.17-alpine
        container_name: toner-nginx
        restart: unless-stopped
        ports:
            - 15000:80
            - 15001:443
        volumes: 
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks: 
            - toner
    
networks:
    toner:
        driver: bridge
